import type { Metadata } from "next";
import type { Viewport } from "next";
import "./globals.css";
import { Julius_Sans_One } from "next/font/google";
import { ThemeContextProvider } from "./providers/ThemeContextProvider";
import { SessionWrapper } from "./providers/SessionWrapper";
import NavBar from "@/components/NavBar";

const julius_sans = Julius_Sans_One({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Done n' Dusted",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${julius_sans.className} antialiased`}
      suppressHydrationWarning
    >
      <body className="h-screen flex flex-col">
        <ThemeContextProvider>
          <SessionWrapper>
            <NavBar />
            {children}
          </SessionWrapper>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
