import type { Metadata } from "next";
import type { Viewport } from "next";
import "./globals.css";
import { Julius_Sans_One } from "next/font/google";
import { Providers } from "./provider";
import NavBar from "@/components/NavBar";

const julius_sans = Julius_Sans_One({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Done n' Dusted",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={julius_sans.className} suppressHydrationWarning>
      <body className="h-screen flex flex-col">
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
